config/routes.rb
Rails.application.routes.draw do

  get 'lends/new'
  get 'lends/index'
  get 'lends/show'
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root to: 'homes#top'

	resources :categories, only: [:index, :create, :edit, :update, :destroy]
	resources :books
	resources :borrowers
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	attachment :image
	belongs_to :category, dependent: :destroy
	has_many :lends, dependent: :destroy
end

app/models/borrower.rb
class Borrower < ApplicationRecord
	has_many :lends, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books, dependent: :destroy
end

app/models/lend.rb
class Lend < ApplicationRecord
	belongs_to :book, dependent: :destroy
	belongs_to :borrower, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protected

	# ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
		books_path
  end

	# ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
		root_path
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def new
		@book = Book.new
	end

	def index
		@books = Book.all
	end

	def create
    @book = Book.new(book_params)
    if @book.save
    	redirect_to books_path, notice: "書籍を追加しました"
    else
    	render :new
		end
	end

	def show
		@book = Book.find(params[:id])
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    	redirect_to book_path(product.id), notice: "書籍情報を変更しました"
    else
  		render :edit
		end
	end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "削除しました"
  end

	private
	def book_params
	  params.require(:book).permit(:category_id, :image, :title, :book_num, :author_name, :publisher, :memo)
	end
end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  def new
  	@borrower = Borrower.new
  end

  def index
    @borrowers = Borrowers.all
    @borrower = Borrower.find(params[id])
  end


  def create
    @borrower = Borrower.new(category_params)
    if @borrower.save
       redirect_to borrowers_path(@borrower), notice: "会員を登録しました。"
    else
      render :new
    end
  end

  def show
		@borrower = Borrower.find(params[:id])
	end

  def edit
  	@borrower = Borrower.find(params[:id])
  end

  def update
  	@borrower = Borrower.find(params[:id])
  	if @borrower.update(borrower_params)
  	   redirect_to borrowers_path(@borrower.id), notice: "会員情報を変更しました"
  	else
  	  render :edit
  	end
  end

  def destroy
  	@borrower = Borrower.find(params[:id])
  	@borrower.destroy
  	redirect_to borrowers_path, notice: "会員情報を削除しました"
  end

  private

  def borrower_params
  	params.require(:borrower).permit(:name, :name_kana, :address, :phone, :remarks)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
       redirect_to categories_path(@category), notice: "ジャンルを追加しました"
    else
      @categories = Category.all
      render :index
    end
  end

  def edit
  	@category = Category.find(params[:id])
  end

  def update
  	@category = Category.find(params[:id])
  	if @category.update(category_params)
  	   redirect_to categories_path(@category.id), notice: "ジャンルを変更しました"
		  if @category.is_active == false
 	  		@category.books.each do |book|
 	  			book.is_active =false
 	  			book.save
 	  		end
  	  end
  	else
  	  render :edit
  	end
  end

  def destroy
  	@category = Category.find(params[:id])
  	@category.destroy
  	redirect_to categories_path, notice: "削除しました"
  end

  private

  def category_params
  	params.require(:category).permit(:category_name, :is_active)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lends_controller.rb
class LendsController < ApplicationController
  def new
  end

  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lends_helper.rb
module LendsHelper
end

app/views/books/_form.html.erb
<div class="col-md-6 offset-md-3 text-center">
  <%= form_with model:book, url:books_path(book), method: :patch, local: true do |f| %>

    <div class="row">
      <div class="col-md-3 text-left">
        <span>画像</span>
      </div>
      <div class="col-md-8 text-left">
        <%= f.attachment_field :image %>
      </div>
    </div>

    <div class="row">
      <div class="col-3 text-left">
        <span>タイトル</span>
      </div>
      <div class="col-md-8">
        <%= f.text_field :title, class:"form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-3 text-left">
        <span>著者名</span>
      </div>
      <div class="col-md-8">
        <%= f.text_field :author_name, class:"form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-3 text-left">
        <span>出版社</span>
      </div>
      <div class="col-md-8">
        <%= f.text_field :publisher, class:"form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-3 text-left">
        <span>ジャンル</span>
      </div>
      <div class="col-md-8">
        <%= f.collection_select :category_id, Category.all, :id, :category_name, {prompt: "選択してください"},{ class: "form-control"} %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3 text-left">
        <span>書籍管理番号</span>
      </div>
      <div class="col-md-8">
        <%= f.text_field :book_num, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-3 text-left">
        <span>メモ</span>
      </div>
      <div class="col-md-8">
          <%= f.text_area :memo, class:"form-control" %>
        </div>
    </div>

    <%= f.submit "保存", class: "button" %>

  <% end %>
</div>

app/views/books/edit.html.erb
<div class= "container-fluid">

  <div class= "row">
    <div class="col-md-4 offset-md-4 text-center">
      <h3>書籍情報編集</h3>
    </div>
  </div>
  <div class="row">
    <%= render "books/form", book: @book %>
  </div>

</div>

app/views/books/index.html.erb
<div class= "container-fluid">
  <div class= "row">

    <div class="col-md-8 offset-md-1 left-content">
      <div class="row">
        <div class="col-md">
          <h3>蔵書一覧</h3>
          <table class="table table-hover table-borderless col-md ">
            <thead>
              <tr>
                <th>管理番号</th>
                <th>タイトル</th>
                <th>著者</th>
                <th>出版社</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= book.book_num %>
                  </td>
                  <td><%= link_to book.title, book_path(book) %>
                  </td>
                  <td>
                    <%= book.author_name %>
                  </td>
                  <td>
                    <%= book.publisher %>
                  </td>
                  <td>
                    <% if book.is_active == true %>
                        <%= "" %>
                      <% else %>
                        <%= "貸出中" %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to "編集", edit_book_path(book), class: "glyphicon glyphicon-pencil btn-sm btn-success" %>
                  </td>
                  <td>
                    <%= link_to "削除", book_path(book), method: :delete, class: "glyphicon glyphicon-pencil btn-sm btn-danger" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

app/views/books/new.html.erb
<div class= "container-fluid">

  <div class= "row">
    <div class="col-md-4 offset-md-4 text-center">
      <h3>新規書籍登録</h3>
    </div>
  </div>

  <div class="row">
    <%= render "books/form", book: @book %>
  </div>

</div>

app/views/books/show.html.erb
 <div class= "container-fluid">
  <div class= "row">

    <div class="col-md-8 offset-md-1 left-content">
      <div class="row">
        <div class="col-md">
          <h3>蔵書詳細</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <%= attachment_image_tag @book, :image, :fill, 100, 100, format: "jpg", fallback: "no-image.jpg" %>
        </div>
        <div class="col-md-9 offset-md-5">
          <%= @book.book_num %>
          <br><%= @book.author_name %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 offset-md-2">
          <p>@book.publisher</p>
          <p>@book.memo</p>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/borrowers/edit.html.erb
<h1>Borrowers#edit</h1>
<p>Find me in app/views/borrowers/edit.html.erb</p>

app/views/borrowers/index.html.erb
<div class= "container-fluid">
  <div class= "row">

    <div class="col-md-8 offset-md-1 left-content">
      <div class="row">
        <div class="col-md">
          <h3>会員情報一覧</h3>
          <table class="table table-hover table-borderless col-md ">
            <thead>
              <tr>
                <th>名前</th>
                <th>ナマエ</th>
                <th>備考</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @borowers.each do |borrower| %>
                <tr>
                  <td class="text-left">
                    <%= borrower.name %>
                  </td>
                  <td><%= borrower.name_kana %>
                  </td>
                  <td><%= borrower.remarks %>
                  </td>
                  <td>
                    <%= link_to "詳細", borrowers_path(borrower), class: "glyphicon glyphicon-pencil btn-sm btn-info" %>
                  </td>
                  <td>
                    <%= link_to "編集", edit_borrower_path(borrower), class: "glyphicon glyphicon-pencil btn-sm btn-success" %>
                  </td>
                  <td>
                    <%= link_to "削除", borrower_path(borrower), method: :delete, class: "glyphicon glyphicon-pencil btn-sm btn-danger" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-md-3 right-content">
      <div class= "row">
        <div class="col-md">
          <%= link_to "新規会員会員登録", new_borrower_path(borrower), class: "button" %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/borrowers/new.html.erb
<div class= "container-fluid">

  <div class= "row">
    <div class="col-md-4 offset-md-4 text-center">
      <h3>新規会員登録</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 offset-md-3 text-center">
      <%= form_with model:@borrower, url:borrowers_path(@borrower), method: :patch, local: true do |f| %>

        <div class="row">
          <div class="col-3 text-left">
            <span>名前</span>
          </div>
          <div class="col-md-8">
            <%= f.text_field :name, class:"form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-3 text-left">
            <span>ナマエ</span>
          </div>
          <div class="col-md-8">
            <%= f.text_field :name_kana, class:"form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-3 text-left">
            <span>住所</span>
          </div>
          <div class="col-md-8">
            <%= f.text_field :address, class:"form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-3 text-left">
            <span>電話番号</span>
          </div>
          <div class="col-md-8">
            <%= f.text_field :phone class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-3 text-left">
            <span>備考</span>
          </div>
          <div class="col-md-8">
              <%= f.text_area :remarks, class:"form-control" %>
            </div>
        </div>

        <%= f.submit class: "button" %>

      <% end %>
    </div>
  </div>

</div>

app/views/borrowers/show.html.erb
<h1>Borrowers#show</h1>
<p>Find me in app/views/borrowers/show.html.erb</p>

app/views/categories/_form.html.erb
<%= form_with model:category, local: true do |f| %>
    <div class="col-md">
      <%= f.text_field :category_name, autofocus: true, placeholder:"新規ジャンル名" %>
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block;"} %>
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, "無効", {value: :false, style: "display: inline-block;"} %>
    </div>
    <div class="col-md text-right">
      <%= f.submit "保存", class: "button" %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<div class= "container-fluid">

  <div class= "row">
    <div class="col-md-4 offset-md-4 text-center">
      <h3>ジャンル編集</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 offset-md-3 text-center">
       <%= render "categories/form", category: @category %>
    </div>
  </div>

</div>

app/views/categories/index.html.erb
<div class= "container-fluid">
  <div class= "row">

    <div class="col-md-8 offset-md-1 left-content">
      <div class="row">
        <div class="col-md">
          <h3>ジャンル一覧</h3>
          <table class="table table-hover table-borderless col-md ">
            <thead>
              <tr>
                <th>ジャンル</th>
                <th>状態</th>
                <th colspan="2"></th>
              </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
                <tr>
                  <td class="text-left">
                    <%= category.category_name %>
                  </td>
                  <% if category.is_active == true %>
                    <td>有効</td>
                  <% else category.is_active == false %>
                    <td>無効</td>
                  <% end %>
                  <td>
                    <%= link_to "編集", edit_category_path(category), class: "glyphicon glyphicon-pencil btn-sm btn-success" %>
                  </td>
                  <td>
                    <%= link_to "削除", category_path(category), method: :delete, class: "glyphicon glyphicon-pencil btn-sm btn-danger" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-md-3 right-content">
      <div class= "row">
        <div class="col-md">
          <h3>ジャンル追加</h3>
           <%= render "categories/form", category: @category %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/homes/top.html.erb
<div class= "container-fluid">
  <div class="top-login">
    <h2>管理者専用 図書管理システム</h2>
    <div class="top-login-btn">
      <% if admin_signed_in? %>
        <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "button-delete"%>
      <% else %>
        <%= link_to 'ログイン', new_admin_session_path, class: "button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollectionManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <header>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top navbar-custom">
          <%= link_to "図書管理", root_path, class: "navbar-brand  mb-0 h1 brand" %>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
              <% if admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to '', books_path, class: "nav-link fas fa-book fa-lg" %>
                </li>
                <li class="nav-item">
                  <%= link_to '書籍新規追加', new_book_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'ジャンル一覧', categories_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete , class: "nav-link" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'ログインしてください', new_admin_session_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>

          <div id="sp-menu">
            <ul>
              <% if admin_signed_in? %>
                <li><%= link_to '書籍新規追加', new_book_path %>
                </li>
                <li><%= link_to '蔵書一覧', books_path %>
                </li>
                <li><%= link_to 'ジャンル一覧', categories_path %>
                </li>
                <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
                </li>
              <% else %>
                <li><%= link_to 'ログインしてください', new_admin_session_path %>
                </li>
                <li><%= link_to '新規管理者登録はこちら', new_admin_registration_path %>
                </li>
              <% end %>
            </ul>
          </div>

          <div id="hm-icon">
            <a class="menu-trigger" href="#">
              <span></span>
              <span></span>
              <span></span>
            </a>
          </div>
        </nav>
      </header>
      <main>
        <div class= "row flash">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
      </main>
    </div>
  </body>

</html>

app/views/lends/index.html.erb
<h1>Lends#index</h1>
<p>Find me in app/views/lends/index.html.erb</p>

app/views/lends/new.html.erb
<h1>Lends#new</h1>
<p>Find me in app/views/lends/new.html.erb</p>

app/views/lends/show.html.erb
<h1>Lends#show</h1>
<p>Find me in app/views/lends/show.html.erb</p>